server:
  port: 8083
  address: localhost

  # 0.0.0.0 for docker
  # 192.168.42.111 for docker
  # localhost for localhost

spring:
  ldap:
    embedded:
      base-dn: dc=embedded,dc=ldap
      credential:
        username: uid=admin
        password: secret
      ldif: classpath:config.ldif
      port: 8084
      validation:
        enabled: false