server:
  port: 8086
  address: localhost

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8082"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: backend
          uri: http://localhost:8081/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/backend/**
        - id: pictures
          uri: http://localhost:8087/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/mongo/**
        - id: keycloak
          uri: http://localhost:8080/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/auth/**