server:
  port: 8086
  address: 0.0.0.0

  # 0.0.0.0 for docker
  # 192.168.42.111 for docker
  # localhost for localhost

  # named as service

spring:
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "http://localhost:8082"
            allowedMethods: "*"
            allowedHeaders: "*"
            allowCredentials: true
        add-to-simple-url-handler-mapping: true
      routes:
        - id: backend
          uri: http://backend:8081/
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/backend/**
        - id: pictures
          uri: http://pictures:8087
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/api/mongo/**
        - id: keycloak
          uri: http://keycloak:8080
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
          predicates:
            - Path=/auth/**