version: "3.9"

services:
  backend:
    image: 'backend'
    ports:
      - 8081:8081
    container_name: backend
#    depends_on:
#      - postgresdb
#      - keycloak

  frontend:
    image: 'frontend'
    ports:
      - 8082:8082
    container_name: frontend

  embedded-ldap:
    image: 'embedded-ldap'
    ports:
      - 8083:8084
    container_name: embedded-ldap

  pictures:
    image: 'pictures'
    ports:
      - 8087:8087
    container_name: pictures
#    depends_on:
#      - mongodb
#      - keycloak

  gateway:
    image: 'gateway'
    ports:
      - 8086:8086
    container_name: gateway

  keycloak:
    image: 'jboss/keycloak:latest'
    ports:
      - 8080:8080
    container_name: keycloak
#    command: ["-Djboss.http.port=8085"]
#    depends_on:
#      - postgresdb
    environment:
      - DB_ADDR=postgresdb
      - DB_PORT=5432
      - DB_DATABASE=keycloak
      - DB_USER=postgres
      - DB_PASSWORD=kiril
      - DB_VENDOR=postgres
#      - KEYCLOAK_USER=admin
#      - KEYCLOAK_PASSWORD=admin
#      - PROXY_ADDRESS_FORWARDING=true
      - KEYCLOAK_FRONTEND_URL=http://keycloak:8080/auth

  mongodb:
    image: 'mongo:4.0.6'
    ports:
      - 27017:27017
    container_name: mongodb
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
    volumes:
      - C:/Users/Kiril/Desktop/mongodb/linuxData:/data/db
      - C:/Users/Kiril/Desktop/mongodb/mongodb-database-tools-windows-x86_64-100.5.1/bin/dump/pictures:/var/dump

  postgresdb:
    image: 'postgres:13.2'
    ports:
      - 5432:5432
    container_name: postgresdb
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=kiril
      - LANG=en_US.UTF-8
    volumes:
      - C:/Users/Kiril/Desktop/pgsql/linuxData:/var/lib/postgresql/data